import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './StronzoSetupScreen.css'

const CATEGORIES = {
  cibi: {
    name: 'Cibi',
    words: [
      'Pizza',
      'Pasta',
      'Risotto',
      'Lasagna',
      'Tiramisù',
      'Cannoli',
      'Gelato',
      'Panna Cotta',
      'Bruschetta',
      'Carbonara',
      'Amatriciana',
      'Cacio e Pepe',
      'Osso Buco',
      'Cotoletta',
      'Parmigiana',
      'Focaccia',
      'Panettone',
      'Crostata',
      'Zeppole',
      'Cannelloni',
      'Arancini',
      'Suppli',
      'Gnocchi',
      'Ravioli',
      'Tortellini',
      'Tagliatelle',
      'Spaghetti',
      'Penne',
      'Fusilli',
      'Rigatoni',
      'Minestrone',
      'Ribollita',
      'Bistecca',
      'Saltimbocca',
      'Vitello Tonnato',
      'Carpaccio',
      'Bresaola',
      'Prosciutto',
      'Salame',
      'Mortadella',
      'Mozzarella',
      'Parmigiano',
      'Gorgonzola',
      'Pecorino',
      'Ricotta',
      'Burrata',
      'Stracciatella',
      'Mascarpone',
      'Sorbetto',
      'Semifreddo',
      'Sfogliatella',
      'Pastiera',
      'Cassata',
      'Biscotti',
      'Cantucci',
      'Amaretti',
      'Baci di Dama',
      'Torta Caprese',
      'Torta della Nonna',
      'Brioche',
      'Frittata',
      'Uova',
      'Pancetta',
      'Guanciale',
      'Lardo',
      'Culatello',
      'Cotechino',
      'Zampone',
      'Bollito',
      'Polenta',
      'Pane',
      'Burro',
      'Olio',
      'Aceto',
      'Sale',
      'Pepe',
      'Zucchero',
      'Miele',
      'Marmellata',
      'Nutella',
      'Cioccolato',
      'Caffè',
      'Tè',
      'Latte',
      'Yogurt',
      'Formaggio',
      'Pollo',
      'Manzo',
      'Maiale',
      'Pesce',
      'Tonno',
      'Salmone',
      'Gamberi',
      'Vongole',
      'Cozze',
      'Pomodoro',
      'Insalata',
      'Carota',
      'Patata',
      'Cipolla',
      'Aglio',
      'Basilico',
      'Prezzemolo',
      'Limone',
      'Arancia',
      'Mela',
      'Banana',
      'Fragola',
      'Uva',
      'Pesca',
      'Pera',
      'Kiwi',
      'Ananas',
      'Anguria',
      'Melone',
      'Ciliegia',
      'Lampone',
      'Mirtillo',
      'Mandarino',
      'Pompelmo',
      'Avocado',
      'Zucchina',
      'Melanzana',
      'Peperone',
      'Broccoli',
      'Cavolfiore',
      'Asparagi',
      'Carciofi',
      'Funghi',
      'Noci',
      'Mandorle',
      'Pistacchi',
      'Arachidi',
      'Olive',
      'Capperi',
      'Acciughe',
      'Sardine',
      'Branzino',
      'Orata',
      'Trota',
      'Sgombro',
      'Calamari',
      'Polpo',
      'Seppia',
      'Aragosta',
      'Granchio',
      'Caviale',
      'Tacchino',
      'Coniglio',
      'Agnello',
      'Vitello',
      'Salsiccia',
      'Hamburger',
      'Hot Dog',
      'Patatine',
      'Popcorn',
      'Ciambella',
      'Waffle',
      'Pancake',
      'Toast',
      'Cornetto',
      'Bombolone',
      'Profiterole',
      'Mousse',
      'Crema',
      'Panna',
      'Panna Montata',
      'Zabaione',
      'Budino',
      'Flan',
      'Cheesecake',
      'Brownie',
      'Muffin',
      'Cupcake',
      'Cracker',
      'Grissini',
      'Taralli',
      'Piadina',
      'Torta',
      'Croissant',
      'Baguette',
      'Ciabatta',
      'Pita',
      'Naan',
      'Sushi',
      'Sashimi',
      'Ramen',
      'Tacos',
      'Burrito',
      'Quesadilla',
      'Nachos',
      'Fajitas',
      'Enchilada',
      'Paella',
      'Tapas',
      'Gazpacho',
      'Ratatouille',
      'Bouillabaisse',
      'Coq au Vin',
      'Schnitzel',
      'Sauerbraten',
      'Goulash',
      'Borscht',
      'Pierogi',
      'Kebab',
      'Falafel',
      'Hummus',
      'Tzatziki',
      'Baba Ganoush',
      'Dolma',
      'Baklava',
      'Lokum',
      'Manti',
      'Shawarma',
      'Pho',
      'Pad Thai',
      'Curry',
      'Biryani',
      'Tandoori',
      'Tikka',
      'Samosa',
      'Roti',
      'Dosa',
      'Idli',
      'Sambar',
      'Chutney',
      'Kimchi',
      'Bibimbap',
      'Bulgogi',
      'Japchae',
      'Tempura',
      'Teriyaki',
      'Yakitori',
      'Okonomiyaki',
      'Takoyaki',
      'Onigiri',
      'Miso',
      'Udon',
      'Soba',
      'Gyoza',
      'Dumpling',
      'Dim Sum',
      'Peking Duck',
      'Kung Pao',
      'Sweet and Sour',
      'General Tso',
      'Mapo Tofu',
      'Hot Pot',
      'Xiaolongbao',
      'Char Siu',
      'Hainanese Rice',
      'Laksa',
      'Nasi Goreng',
      'Satay',
      'Rendang',
      'Gado Gado',
      'Nasi Lemak',
      'Tom Yum',
      'Green Curry',
      'Massaman',
      'Panang',
      'Som Tam',
      'Larb',
      'Sticky Rice',
      'Mango Sticky Rice',
      'Banh Mi',
      'Spring Rolls',
      'Banh Xeo',
      'Bun Cha',
      'Pho Bo',
      'Goi Cuon',
      'Cao Lau',
      'Com Tam',
      'Bo Kho',
      'Banh Cuon',
      'Chuoi Chien',
      'Che',
      'Bun Bo Hue',
      'Mi Quang',
      'Banh Canh',
      'Hu Tieu',
      'Bun Rieu',
      'Canh Chua',
      'Thit Kho',
      'Ga Kho',
      'Ca Kho',
      'Tom Kho',
      'Rau Muong',
      'Goi Du Du',
      'Nem Nuong',
      'Bo La Lot',
      'Chao',
      'Xoi',
      'Banh Chung',
      'Banh Tet',
      'Banh Bao',
      'Banh Bot Loc',
      'Banh Beo',
      'Banh Khot',
      'Banh Trang',
      'Banh Phu The',
      'Banh Pia',
      'Banh Dau Xanh',
      'Banh Deo',
      'Banh Com',
      'Banh Gio',
      'Banh Ran',
      'Banh Cam',
      'Sushi',
      'Tacos',
      'Hamburger',
      'Hot Dog',
      'Patatine',
      'Popcorn',
      'Ciambella',
      'Waffle',
      'Pancake',
      'Toast',
      'Cornetto',
      'Bombolone',
      'Profiterole',
      'Mousse',
      'Crema',
      'Panna',
      'Panna Montata',
      'Zabaione',
      'Budino',
      'Flan',
      'Cheesecake',
      'Brownie',
      'Muffin',
      'Cupcake',
      'Cracker',
      'Grissini',
      'Taralli',
      'Piadina',
      'Torta',
      'Croissant',
      'Baguette',
      'Ciabatta',
      'Pita',
      'Naan',
      'Sashimi',
      'Ramen',
      'Burrito',
      'Quesadilla',
      'Nachos',
      'Fajitas',
      'Enchilada',
      'Paella',
      'Tapas',
      'Gazpacho',
      'Ratatouille',
      'Schnitzel',
      'Goulash',
      'Pierogi',
      'Kebab',
      'Falafel',
      'Hummus',
      'Tzatziki',
      'Baklava',
      'Shawarma',
      'Pho',
      'Pad Thai',
      'Curry',
      'Biryani',
      'Tandoori',
      'Tikka',
      'Samosa',
      'Roti',
      'Chutney',
      'Kimchi',
      'Bibimbap',
      'Tempura',
      'Teriyaki',
      'Yakitori',
      'Onigiri',
      'Miso',
      'Udon',
      'Soba',
      'Gyoza',
      'Dumpling',
      'Dim Sum',
      'Peking Duck',
      'Kung Pao',
      'Sweet and Sour',
      'General Tso',
      'Mapo Tofu',
      'Hot Pot',
      'Char Siu',
      'Satay',
      'Tom Yum',
      'Green Curry',
      'Massaman',
      'Som Tam',
      'Spring Rolls',
      'Banh Mi',
    ],
  },
  oggetti: {
    name: 'Oggetti',
    words: [
      'Telefono',
      'Computer',
      'Libro',
      'Penna',
      'Occhiali',
      'Orologio',
      'Borsa',
      'Chiavi',
      'Portafoglio',
      'Cuffie',
      'Tastiera',
      'Mouse',
      'Lampada',
      'Sedia',
      'Tavolo',
      'Finestra',
      'Porta',
      'Specchio',
      'Fotocamera',
      'Tablet',
      'Stampante',
      'Router',
      'Ventilatore',
      'Radio',
      'Televisore',
      'Frigorifero',
      'Forno',
      'Lavatrice',
      'Aspirapolvere',
      'Ombrello',
      'Zaino',
      'Bicicletta',
      'Automobile',
      'Motocicletta',
      'Anello',
      'Collana',
      'Orecchini',
      'Braccialetto',
      'Martello',
      'Cacciavite',
      'Pinza',
      'Forbici',
      'Coltello',
      'Forchetta',
      'Cucchiaio',
      'Piatto',
      'Bicchiere',
      'Tazza',
      'Bottiglia',
      'Vaso',
      'Cuscino',
      'Coperte',
      'Letto',
      'Armadio',
      'Scrivania',
      'Divano',
      'Poltrona',
      'Tappeto',
      'Tenda',
      'Tovaglia',
      'Asciugamano',
      'Sapone',
      'Shampoo',
      'Dentifricio',
      'Spazzolino',
      'Pettine',
      'Spazzola',
      'Calzini',
      'Scarpe',
      'Cappello',
      'Cappotto',
      'Maglietta',
      'Pantaloni',
      'Gonna',
      'Vestito',
      'Giacca',
      'Sciarpa',
      'Guanti',
      'Occhiali da sole',
      'Borsello',
      'Valigia',
      'Borsa da viaggio',
      'Quaderno',
      'Matita',
      'Gomma',
      'Righello',
      'Astuccio',
      'Calcolatrice',
      'Gesso',
      'Lavagna',
      'Proiettore',
      'Microfono',
      'Altoparlante',
      'Batteria',
      'Caricabatterie',
      'Cavo',
      'Spina',
      'Interruttore',
      'Presa',
      'Lampadina',
      'Candela',
      'Accendino',
    ],
  },
  paesi: {
    name: 'Paesi del Mondo',
    words: [
      'Italia',
      'Francia',
      'Spagna',
      'Germania',
      'Regno Unito',
      'Grecia',
      'Portogallo',
      'Olanda',
      'Belgio',
      'Svizzera',
      'Austria',
      'Svezia',
      'Norvegia',
      'Danimarca',
      'Finlandia',
      'Polonia',
      'Repubblica Ceca',
      'Ungheria',
      'Romania',
      'Croazia',
      'Giappone',
      'Cina',
      'India',
      'Brasile',
      'Argentina',
      'Messico',
      'Canada',
      'Stati Uniti',
      'Australia',
      'Nuova Zelanda',
      'Sudafrica',
      'Egitto',
      'Marocco',
      'Turchia',
      'Russia',
      'Corea del Sud',
      'Thailandia',
      'Vietnam',
      'Indonesia',
      'Filippine',
      'Singapore',
      'Malaysia',
      'Irlanda',
      'Islanda',
      'Lussemburgo',
      'Monaco',
      'Andorra',
      'San Marino',
      'Vaticano',
      'Malta',
      'Cipro',
      'Bulgaria',
      'Serbia',
      'Slovenia',
      'Slovacchia',
      'Estonia',
      'Lettonia',
      'Lituania',
      'Bielorussia',
      'Ucraina',
      'Moldavia',
      'Albania',
      'Macedonia',
      'Bosnia',
      'Montenegro',
      'Kosovo',
      'Israele',
      'Palestina',
      'Giordania',
      'Libano',
      'Siria',
      'Iraq',
      'Iran',
      'Afghanistan',
      'Pakistan',
      'Bangladesh',
      'Sri Lanka',
      'Nepal',
      'Bhutan',
      'Myanmar',
      'Cambogia',
      'Laos',
      'Corea del Nord',
      'Mongolia',
      'Kazakistan',
      'Uzbekistan',
      'Tagikistan',
      'Kirghizistan',
      'Turkmenistan',
      'Azerbaigian',
      'Armenia',
      'Georgia',
      'Arabia Saudita',
      'Emirati Arabi',
      'Qatar',
      'Kuwait',
      'Bahrein',
      'Oman',
      'Yemen',
      'Kenya',
      'Tanzania',
      'Etiopia',
      'Nigeria',
      'Ghana',
      'Senegal',
      'Tunisia',
      'Algeria',
      'Libia',
      'Cile',
      'Perù',
      'Colombia',
      'Venezuela',
      'Ecuador',
      'Uruguay',
      'Paraguay',
      'Bolivia',
      'Cuba',
      'Giamaica',
      'Haiti',
      'Repubblica Dominicana',
      'Costa Rica',
      'Panama',
      'Guatemala',
      'Honduras',
      'El Salvador',
      'Nicaragua',
    ],
  },
}

export default function StronzoSetupScreen() {
  const navigate = useNavigate()
  const [numPlayers, setNumPlayers] = useState(4)
  const [selectedCategories, setSelectedCategories] = useState({
    cibi: true,
    oggetti: true,
    paesi: true,
  })
  const [playerNames, setPlayerNames] = useState(['', '', '', ''])

  const toggleCategory = (category) => {
    setSelectedCategories((prev) => ({
      ...prev,
      [category]: !prev[category],
    }))
  }

  const updateNumPlayers = (delta) => {
    const newNum = Math.max(3, Math.min(12, numPlayers + delta))
    setNumPlayers(newNum)
    const newNames = Array(newNum)
      .fill('')
      .map((_, i) => playerNames[i] || `Giocatore ${i + 1}`)
    setPlayerNames(newNames)
  }

  const updatePlayerName = (index, name) => {
    const newNames = [...playerNames]
    newNames[index] = name || `Giocatore ${index + 1}`
    setPlayerNames(newNames)
  }

  const startGame = () => {
    const activeCategories = Object.keys(selectedCategories).filter(
      (cat) => selectedCategories[cat]
    )

    if (activeCategories.length === 0) {
      alert('Seleziona almeno una categoria!')
      return
    }

    if (numPlayers < 3) {
      alert('Servono almeno 3 giocatori!')
      return
    }

    // Calcola numero di stronzi (circa 1 ogni 4 giocatori, minimo 1)
    const numStronzi = Math.max(1, Math.floor(numPlayers / 4))

    navigate('/stronzo/game', {
      state: {
        numPlayers,
        playerNames: playerNames.slice(0, numPlayers),
        categories: activeCategories,
        numStronzi,
        allWords: activeCategories.reduce((acc, cat) => {
          return [...acc, ...CATEGORIES[cat].words]
        }, []),
      },
    })
  }

  return (
    <div className="setup-screen">
      <div className="setup-content">
        <button className="back-button" onClick={() => navigate('/')}>
          ← INDIETRO
        </button>
        <h2 className="setup-title">STRONZO</h2>

        <div className="setup-section">
          <h3 className="section-title">NUMERO GIOCATORI</h3>
          <div className="num-players-container">
            <button className="num-button" onClick={() => updateNumPlayers(-1)}>
              −
            </button>
            <input
              type="number"
              className="num-input"
              value={numPlayers}
              onChange={(e) => {
                const val = parseInt(e.target.value) || 3
                setNumPlayers(Math.max(3, Math.min(12, val)))
                const newNames = Array(val)
                  .fill('')
                  .map((_, i) => playerNames[i] || `Giocatore ${i + 1}`)
                setPlayerNames(newNames)
              }}
              min="3"
              max="12"
            />
            <button className="num-button" onClick={() => updateNumPlayers(1)}>
              +
            </button>
          </div>
        </div>

        <div className="setup-section">
          <h3 className="section-title">NOMI GIOCATORI</h3>
          <div className="names-container">
            {playerNames.slice(0, numPlayers).map((name, index) => (
              <input
                key={index}
                type="text"
                className="name-input"
                placeholder={`Giocatore ${index + 1}`}
                value={name}
                onChange={(e) => updatePlayerName(index, e.target.value)}
              />
            ))}
          </div>
        </div>

        <div className="setup-section">
          <h3 className="section-title">CATEGORIE</h3>
          <div className="categories-container">
            {Object.keys(CATEGORIES).map((key) => (
              <button
                key={key}
                className={`category-button ${
                  selectedCategories[key] ? 'active' : ''
                }`}
                onClick={() => toggleCategory(key)}
              >
                {CATEGORIES[key].name}
              </button>
            ))}
          </div>
        </div>

        <button className="start-button" onClick={startGame}>
          INIZIA
        </button>
      </div>
    </div>
  )
}
